app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
# For Swagger UI    
#app.swagger_ui:
#    path: /api/doc
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
    
#app.swagger:
#    path: /api/doc.json
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger }

# For rest api
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    
    
  