# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
# For rest api            
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
# For rest api            
        fos_userbundle:
            #id: fos_user.user_provider.id
            id: fos_user.user_provider.username        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)
            #id: fos_user.user_manager.username 
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false
            #security: true

        #main:
        #    anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
# For rest api            
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        api:
            pattern: ^/                            
            fos_oauth: true                            
            stateless: true                           
            anonymous: false  
            
    